"""Mock AI provider.

Produces realistic, schema-valid SOC investigation output entirely offline so
the platform is fully usable with zero API keys (demo / air-gapped mode). The
logic is heuristic but evidence-based and conservative: weak evidence yields a
"Needs Review" verdict.
"""
from __future__ import annotations

import json
import time

from app.ai.base import AIProvider, estimate_tokens
from app.ai.schemas import (
    AIRequest,
    AIResponse,
    ProviderHealth,
    TokenUsage,
    empty_investigation,
)


class MockAIProvider(AIProvider):
    name = "mock"
    is_local = True

    def __init__(self, model: str | None = "mock-soc-1"):
        super().__init__(model or "mock-soc-1")

    async def generate(self, request: AIRequest) -> AIResponse:
        started = time.perf_counter()
        ctx = request.metadata or {}
        prompt_type = request.prompt_type or "generic"

        if request.json_mode or prompt_type in {
            "soc_investigation",
            "alert_parser",
            "qa_review",
        }:
            text = json.dumps(self._structured(prompt_type, ctx, request))
        else:
            text = self._freeform(prompt_type, ctx)

        usage = TokenUsage(
            input_tokens=sum(estimate_tokens(m.content) for m in request.messages),
            output_tokens=estimate_tokens(text),
        )
        return self._finalize(text, self.model or "mock-soc-1", usage, started)

    async def health_check(self) -> ProviderHealth:
        return ProviderHealth(
            provider=self.name,
            configured=True,
            healthy=True,
            is_local=True,
            model=self.model,
            detail="Mock provider always available (offline demo mode).",
            latency_ms=1,
        )

    # ------------------------------------------------------------------ helpers
    def _freeform(self, prompt_type: str, ctx: dict) -> str:
        alert = ctx.get("alert_name", "the alert")
        if prompt_type == "report_writer":
            return f"SOC investigation report for {alert} generated by the mock provider."
        if prompt_type == "customer_email_prompt":
            return (
                f"Dear Customer,\n\nWe investigated an alert titled '{alert}'. "
                "Based on current evidence, further validation is recommended.\n\n"
                "Regards,\nSOC Team"
            )
        return f"[mock-{prompt_type}] Response generated offline for: {alert}"

    def _structured(self, prompt_type: str, ctx: dict, request: AIRequest) -> dict:
        if prompt_type == "alert_parser":
            return ctx.get("parsed_hint", {})
        if prompt_type == "qa_review":
            return self._qa(ctx)
        return self._investigation(ctx)

    def _investigation(self, ctx: dict) -> dict:
        result = empty_investigation()
        alert_name = ctx.get("alert_name", "Security Alert")
        category = (ctx.get("category") or "generic").lower()
        src_ip = ctx.get("src_ip")
        dest_ip = ctx.get("dest_ip")
        username = ctx.get("username")
        hostname = ctx.get("hostname")
        domain = ctx.get("domain")
        file_hash = ctx.get("file_hash")
        severity = ctx.get("severity", "Medium")
        allowlisted = bool(ctx.get("allowlisted"))
        malicious_iocs = ctx.get("malicious_iocs", [])
        correlated = ctx.get("correlation_count", 0)
        prior_fp = bool(ctx.get("prior_false_positive"))

        facts: list[str] = [f"Alert '{alert_name}' was received from {ctx.get('source_tool', 'a security tool')}."]
        if src_ip:
            facts.append(f"Source IP observed: {src_ip}.")
        if dest_ip:
            facts.append(f"Destination IP observed: {dest_ip}.")
        if username:
            facts.append(f"Associated username: {username}.")
        if hostname:
            facts.append(f"Associated host: {hostname}.")
        if domain:
            facts.append(f"Domain observed: {domain}.")
        if file_hash:
            facts.append(f"File hash observed: {file_hash}.")

        missing = [
            "Authentication outcome (success vs failure) for each attempt.",
            "Whether the source IP is a known/sanctioned scanner or jump host.",
            "Endpoint process and parent-process telemetry around the event time.",
            "Customer confirmation of expected activity / maintenance windows.",
        ]

        # Heuristic verdict and confidence -------------------------------------
        confidence = 40
        verdict = "Needs Review"
        evidence_strength = len([f for f in [src_ip, username, file_hash, domain] if f])

        if malicious_iocs:
            verdict = "True Positive"
            confidence = min(85, 60 + 10 * len(malicious_iocs))
            facts.append(
                f"{len(malicious_iocs)} indicator(s) returned malicious reputation from enrichment."
            )
        elif allowlisted or prior_fp:
            verdict = "Benign Authorized Activity"
            confidence = 70
            facts.append(
                "Indicator matched a customer allowlist / known false-positive pattern."
            )
        elif evidence_strength >= 2 and category in {
            "brute_force",
            "password_spray",
            "web_attack",
            "malware",
            "lateral_movement",
            "c2",
        }:
            verdict = "Needs Review"
            confidence = 55

        if correlated >= 1 and verdict == "True Positive":
            confidence = min(95, confidence + 5)
            facts.append(f"Activity correlates with {correlated} related prior alert(s).")

        # Guardrail: never assert TP/FP without enough evidence
        if verdict in {"True Positive", "False Positive"} and evidence_strength < 2 and not malicious_iocs:
            verdict = "Needs Review"
            confidence = min(confidence, 45)

        result.update(
            {
                "executive_summary": self._exec_summary(alert_name, ctx, verdict),
                "technical_analysis": self._tech_analysis(alert_name, category, ctx),
                "verdict": verdict,
                "confidence_score": confidence,
                "severity_recommendation": severity if severity in
                {"Informational", "Low", "Medium", "High", "Critical"} else "Medium",
                "reasoning_summary": (
                    "Verdict derived from observed indicators, enrichment reputation, "
                    "allowlist matches and historical correlation. This is a summary of "
                    "reasoning, not hidden chain-of-thought."
                ),
                "facts_observed": facts,
                "assumptions": [
                    "Timestamps are assumed accurate and in the customer's timezone.",
                    "No additional out-of-band context was provided beyond the alert.",
                ],
                "evidence": self._evidence(ctx, malicious_iocs),
                "missing_evidence": missing,
                "ioc_summary": ctx.get("ioc_summary", []),
                "mitre_mapping": self._mitre(category),
                "timeline": ctx.get("timeline", []),
                "recommended_actions": self._actions(verdict, category),
                "customer_email_draft": self._email(alert_name, verdict),
                "ticket_update": self._ticket(alert_name, verdict, confidence),
                "investigation_checklist": self._checklist(category),
                "detection_query_suggestions": self._queries(category, ctx),
                "qa_warnings": [],
            }
        )
        return result

    def _exec_summary(self, alert_name: str, ctx: dict, verdict: str) -> str:
        src = ctx.get("src_ip", "an internal/external source")
        return (
            f"SOC received an alert titled '{alert_name}' from "
            f"{ctx.get('source_tool', 'a security tool')}. The alert involves activity "
            f"associated with {src}. Based on the available evidence, the current "
            f"assessment is '{verdict}'. Further validation is recommended to confirm "
            "whether the activity is malicious or expected."
        )

    def _tech_analysis(self, alert_name: str, category: str, ctx: dict) -> str:
        return (
            f"The '{alert_name}' alert was analyzed against the '{category}' playbook. "
            "Observed indicators were cross-referenced with enrichment reputation, "
            "customer allowlists, asset context and historical case correlation. The "
            "analysis separates confirmed facts from assumptions and explicitly lists "
            "missing evidence required to reach a high-confidence verdict."
        )

    def _evidence(self, ctx: dict, malicious_iocs: list) -> list:
        ev = []
        if ctx.get("src_ip"):
            ev.append({"type": "ip", "value": ctx["src_ip"], "source": "alert", "importance": "high"})
        if ctx.get("username"):
            ev.append({"type": "username", "value": ctx["username"], "source": "alert", "importance": "medium"})
        for ioc in malicious_iocs:
            ev.append({"type": "ioc", "value": str(ioc), "source": "enrichment", "importance": "high"})
        return ev

    def _mitre(self, category: str) -> list:
        table = {
            "brute_force": [("Credential Access", "Brute Force", "T1110", 70)],
            "password_spray": [("Credential Access", "Password Spraying", "T1110.003", 75)],
            "malware": [("Execution", "Malicious File", "T1204", 60)],
            "lateral_movement": [("Lateral Movement", "Remote Services: SMB", "T1021.002", 65)],
            "c2": [("Command and Control", "Application Layer Protocol", "T1071", 60)],
            "web_attack": [("Initial Access", "Exploit Public-Facing Application", "T1190", 65)],
            "powershell": [("Execution", "Command and Scripting Interpreter: PowerShell", "T1059.001", 70)],
            "dns": [("Command and Control", "DNS", "T1071.004", 55)],
            "credential_dumping": [("Credential Access", "OS Credential Dumping", "T1003", 75)],
        }
        items = table.get(category, [("Discovery", "System Information Discovery", "T1082", 40)])
        return [
            {
                "tactic": t,
                "technique": tech,
                "technique_id": tid,
                "confidence": conf,
                "reason": f"Alert characteristics are consistent with {tech}.",
            }
            for (t, tech, tid, conf) in items
        ]

    def _actions(self, verdict: str, category: str) -> list:
        # All response actions are recommendation-only and require human approval.
        base = [
            {
                "action": "Validate the authentication outcome and affected accounts in the SIEM/IdP logs.",
                "priority": "high",
                "requires_human_approval": True,
                "reason": "Confirms whether attempts succeeded before any containment.",
            },
            {
                "action": "Confirm with the customer whether the source is expected (scanner, VPN, maintenance).",
                "priority": "medium",
                "requires_human_approval": True,
                "reason": "Distinguishes authorized activity from malicious behaviour.",
            },
        ]
        if verdict == "True Positive":
            base.append(
                {
                    "action": "Recommend resetting affected credentials and reviewing session tokens (human-approved).",
                    "priority": "high",
                    "requires_human_approval": True,
                    "reason": "Limits attacker access if credentials were compromised.",
                }
            )
        return base

    def _email(self, alert_name: str, verdict: str) -> str:
        return (
            f"Subject: SOC Notification — {alert_name}\n\n"
            "Dear Team,\n\n"
            f"Our SOC investigated an alert titled '{alert_name}'. The current assessment "
            f"is '{verdict}'. We recommend validating the highlighted activity and will "
            "update this ticket as additional evidence is gathered.\n\n"
            "Kind regards,\nSOC Analyst Team"
        )

    def _ticket(self, alert_name: str, verdict: str, confidence: int) -> str:
        return (
            f"Investigated '{alert_name}'. Current verdict: {verdict} "
            f"(confidence {confidence}%). Evidence and missing-evidence captured in the "
            "investigation record. Awaiting validation steps before closure."
        )

    def _checklist(self, category: str) -> list:
        return [
            "Confirm event timestamps and timezone.",
            "Verify whether source IP is a known/sanctioned host.",
            "Check authentication success vs failure counts.",
            "Review endpoint process telemetry around the event.",
            "Correlate with prior cases and analyst feedback.",
            "Confirm expected maintenance windows with the customer.",
        ]

    def _queries(self, category: str, ctx: dict) -> dict:
        user = ctx.get("username", "<user>")
        src = ctx.get("src_ip", "<src_ip>")
        return {
            "splunk": (
                f"index=security sourcetype=auth src_ip={src} "
                "| stats count, dc(user) as distinct_users by src_ip, dest "
                "| where distinct_users > 5"
            ),
            "crowdstrike_logscale": (
                f'#event_simpleName=UserLogonFailed RemoteIP="{src}" '
                "| groupBy([RemoteIP, UserName], function=count()) | sort(_count, order=desc)"
            ),
            "wazuh": (
                "rule idea: trigger when >5 failed authentications from one src_ip within 5m; "
                "decoder: windows_eventchannel; fields: srcip, win.eventdata.targetUserName"
            ),
            "elastic_kql": (
                f'event.category:"authentication" and source.ip:"{src}" and event.outcome:"failure"'
            ),
            "sigma": (
                "title: Multiple Failed Authentications From Single Source\n"
                "logsource:\n  category: authentication\n"
                "detection:\n  selection:\n    event.outcome: failure\n"
                "  condition: selection | count() by source.ip > 5\n"
                "falsepositives:\n  - Vulnerability scanners\n  - Misconfigured services\n"
                "level: medium"
            ),
            "sentinel_kql": (
                f'SigninLogs | where IPAddress == "{src}" '
                "| summarize attempts=count(), users=dcount(UserPrincipalName) by IPAddress "
                "| where users > 5"
            ),
        }

    def _qa(self, ctx: dict) -> dict:
        warnings = []
        result = ctx.get("investigation_result", {})
        if result.get("verdict") in {"True Positive", "False Positive"} and not result.get("evidence"):
            warnings.append("Verdict asserts TP/FP but no supporting evidence is listed.")
        if (result.get("confidence_score", 0) or 0) >= 80 and len(result.get("missing_evidence", [])) >= 3:
            warnings.append("High confidence despite significant missing evidence.")
        forced = bool(warnings)
        return {
            "qa_warnings": warnings,
            "force_needs_review": forced,
            "passed": not forced,
        }
