"""Built-in SOC playbooks. Triage/investigation steps are advisory; all
containment steps are explicitly human-approved (no automated response)."""
from __future__ import annotations

PLAYBOOKS: list[dict] = [
    {
        "key": "brute_force", "name": "Brute Force Authentication", "category": "Credential Access",
        "description": "Repeated failed authentications against one account.",
        "triage_steps": ["Confirm failed vs successful counts", "Identify target account criticality",
                          "Check source IP reputation/geo"],
        "investigation_steps": ["Correlate with prior auth alerts", "Check for eventual success",
                                "Review MFA status"],
        "containment_steps": ["Recommend account lockout review (human-approved)",
                              "Recommend source IP block at perimeter (human-approved)"],
        "mitre_techniques": ["T1110"],
    },
    {
        "key": "password_spray", "name": "Password Spray", "category": "Credential Access",
        "description": "Few attempts across many accounts from a single source.",
        "triage_steps": ["Count distinct usernames per source", "Identify time window",
                          "Check whether any login succeeded"],
        "investigation_steps": ["Review sign-in logs for success", "Identify targeted account patterns"],
        "containment_steps": ["Recommend conditional access tightening (human-approved)"],
        "mitre_techniques": ["T1110.003"],
    },
    {
        "key": "suspicious_auth", "name": "Suspicious AD Authentication", "category": "Credential Access",
        "description": "Anomalous Active Directory authentication activity.",
        "triage_steps": ["Identify involved accounts/hosts", "Check Kerberos/NTLM patterns"],
        "investigation_steps": ["Review DC logs", "Check for ticket anomalies"],
        "containment_steps": ["Recommend credential reset review (human-approved)"],
        "mitre_techniques": ["T1110", "T1078"],
    },
    {
        "key": "unusual_login", "name": "Unusual Login", "category": "Initial Access",
        "description": "Impossible travel or anomalous geo/device login.",
        "triage_steps": ["Compare to user baseline", "Check device and geo"],
        "investigation_steps": ["Verify with user/customer", "Review session activity"],
        "containment_steps": ["Recommend session revocation review (human-approved)"],
        "mitre_techniques": ["T1078"],
    },
    {
        "key": "new_endpoint", "name": "New Endpoint Login", "category": "Initial Access",
        "description": "First-seen host or device for an account.",
        "triage_steps": ["Confirm asset inventory", "Check enrollment records"],
        "investigation_steps": ["Validate with customer asset list"],
        "containment_steps": ["Recommend device verification (human-approved)"],
        "mitre_techniques": ["T1078"],
    },
    {
        "key": "web_attack", "name": "Web Attack", "category": "Initial Access",
        "description": "Exploitation attempts against public web apps.",
        "triage_steps": ["Identify payload type", "Check WAF action (block/allow)"],
        "investigation_steps": ["Review server response codes", "Check for successful exploitation"],
        "containment_steps": ["Recommend WAF rule tuning (human-approved)"],
        "mitre_techniques": ["T1190"],
    },
    {
        "key": "directory_traversal", "name": "Directory Traversal", "category": "Initial Access",
        "description": "Path traversal attempts in web requests.",
        "triage_steps": ["Identify targeted paths", "Check response codes"],
        "investigation_steps": ["Determine if sensitive files were accessed"],
        "containment_steps": ["Recommend input validation review (human-approved)"],
        "mitre_techniques": ["T1190"],
    },
    {
        "key": "sql_injection", "name": "SQL Injection", "category": "Initial Access",
        "description": "SQLi attempts against web applications.",
        "triage_steps": ["Identify injection strings", "Check WAF/DB error responses"],
        "investigation_steps": ["Review DB logs for anomalous queries"],
        "containment_steps": ["Recommend parameterized query review (human-approved)"],
        "mitre_techniques": ["T1190"],
    },
    {
        "key": "dns", "name": "Suspicious DNS", "category": "Command and Control",
        "description": "Queries to low-reputation or anomalous domains.",
        "triage_steps": ["Check domain reputation", "Identify querying hosts"],
        "investigation_steps": ["Review resolution and subsequent connections"],
        "containment_steps": ["Recommend DNS sinkhole review (human-approved)"],
        "mitre_techniques": ["T1071.004"],
    },
    {
        "key": "malware", "name": "Malware / Suspicious Process", "category": "Execution",
        "description": "Detected malicious file or process behaviour.",
        "triage_steps": ["Confirm detection name and hash", "Check quarantine status"],
        "investigation_steps": ["Review process tree", "Check persistence and network activity"],
        "containment_steps": ["Recommend host isolation review (human-approved)"],
        "mitre_techniques": ["T1204", "T1059"],
    },
    {
        "key": "powershell", "name": "Suspicious PowerShell", "category": "Execution",
        "description": "Encoded or anomalous PowerShell execution.",
        "triage_steps": ["Decode any encoded command", "Identify parent process"],
        "investigation_steps": ["Review script block logging", "Check network egress"],
        "containment_steps": ["Recommend host investigation (human-approved)"],
        "mitre_techniques": ["T1059.001"],
    },
    {
        "key": "lateral_movement", "name": "Lateral Movement", "category": "Lateral Movement",
        "description": "SMB/RDP/WMI lateral movement indicators.",
        "triage_steps": ["Identify source and target hosts", "Check admin share access"],
        "investigation_steps": ["Map movement path", "Review authentication chain"],
        "containment_steps": ["Recommend segmentation review (human-approved)"],
        "mitre_techniques": ["T1021.002", "T1021.001"],
    },
    {
        "key": "waf_attack", "name": "WAF Attack", "category": "Initial Access",
        "description": "Attacks blocked or detected by the WAF.",
        "triage_steps": ["Confirm WAF action", "Identify attack signature"],
        "investigation_steps": ["Check for bypass attempts", "Correlate with backend logs"],
        "containment_steps": ["Recommend signature/policy tuning (human-approved)"],
        "mitre_techniques": ["T1190"],
    },
]
